# Generated by Django 2.0.1 on 2018-01-17 06:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('floor_name', models.CharField(max_length=150)),
                ('serialised_plan_svg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20)),
                ('url', models.TextField(blank=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpsapi.FloorPlan')),
            ],
        ),
        migrations.CreateModel(
            name='PersonAnnotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('label', models.CharField(max_length=200)),
                ('order_num', models.DecimalField(decimal_places=0, max_digits=3)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpsapi.Person')),
            ],
        ),
    ]
